#ifndef _TERRA_KERNEL_CONSTANTS_KEY_CODES_
#define _TERRA_KERNEL_CONSTANTS_KEY_CODES_ 1

#define KEY_SCAN_CODE_ESC                   0x01
#define KEY_SCAN_CODE_1                     0x02
#define KEY_SCAN_CODE_2                     0x03
#define KEY_SCAN_CODE_3                     0x04
#define KEY_SCAN_CODE_4                     0x05
#define KEY_SCAN_CODE_5                     0x06
#define KEY_SCAN_CODE_6                     0x07
#define KEY_SCAN_CODE_7                     0x08
#define KEY_SCAN_CODE_8                     0x09
#define KEY_SCAN_CODE_9                     0x0A
#define KEY_SCAN_CODE_0                     0x0B
#define KEY_SCAN_CODE_MINUS                 0x0C
#define KEY_SCAN_CODE_EQUAL                 0x0D
#define KEY_SCAN_CODE_BACKSPACE             0x0E
#define KEY_SCAN_CODE_TAB                   0x0F
#define KEY_SCAN_CODE_Q                     0x10
#define KEY_SCAN_CODE_W                     0x11
#define KEY_SCAN_CODE_E                     0x12
#define KEY_SCAN_CODE_R                     0x13
#define KEY_SCAN_CODE_T                     0x14
#define KEY_SCAN_CODE_Y                     0x15
#define KEY_SCAN_CODE_U                     0x16
#define KEY_SCAN_CODE_I                     0x17
#define KEY_SCAN_CODE_O                     0x18
#define KEY_SCAN_CODE_P                     0x19
#define KEY_SCAN_CODE_SQUARE_OPEN_BRACKET   0x1A
#define KEY_SCAN_CODE_SQUARE_CLOSE_BRACKET  0x1B
#define KEY_SCAN_CODE_ENTER                 0x1C
#define KEY_SCAN_CODE_LEFT_CTRL             0x1D
#define KEY_SCAN_CODE_A                     0x1E
#define KEY_SCAN_CODE_S                     0x1F
#define KEY_SCAN_CODE_D                     0x20
#define KEY_SCAN_CODE_F                     0x21
#define KEY_SCAN_CODE_G                     0x22
#define KEY_SCAN_CODE_H                     0x23
#define KEY_SCAN_CODE_J                     0x24
#define KEY_SCAN_CODE_K                     0x25
#define KEY_SCAN_CODE_L                     0x26
#define KEY_SCAN_CODE_SEMICOLON             0x27
#define KEY_SCAN_CODE_SINGLE_QUOTE          0x28
#define KEY_SCAN_CODE_ACUTE                 0x29
#define KEY_SCAN_CODE_LEFT_SHIFT            0x2A
#define KEY_SCAN_CODE_BACKSLASH             0x2B
#define KEY_SCAN_CODE_Z                     0x2C
#define KEY_SCAN_CODE_X                     0x2D
#define KEY_SCAN_CODE_C                     0x2E
#define KEY_SCAN_CODE_V                     0x2F
#define KEY_SCAN_CODE_B                     0x30
#define KEY_SCAN_CODE_N                     0x31
#define KEY_SCAN_CODE_M                     0x32
#define KEY_SCAN_CODE_COMMA                 0x33
#define KEY_SCAN_CODE_DOT                   0x34
#define KEY_SCAN_CODE_FORESLHASH            0x35
#define KEY_SCAN_CODE_RIGHT_SHIFT           0x36
#define KEY_SCAN_CODE_ASTERISK              0x37
#define KEY_SCAN_CODE_ALT                   0x38
#define KEY_SCAN_CODE_SPACE                 0x39
#define KEY_SCAN_CODE_CAPS_LOCK             0x3A
#define KEY_SCAN_CODE_F1                    0x3B
#define KEY_SCAN_CODE_F2                    0x3C
#define KEY_SCAN_CODE_F3                    0x3D
#define KEY_SCAN_CODE_F4                    0x3E
#define KEY_SCAN_CODE_F5                    0x3F
#define KEY_SCAN_CODE_F6                    0x40
#define KEY_SCAN_CODE_F7                    0x41
#define KEY_SCAN_CODE_F8                    0x42
#define KEY_SCAN_CODE_F9                    0x43
#define KEY_SCAN_CODE_F10                   0x44
#define KEY_SCAN_CODE_NUM_LOCK              0x45
#define KEY_SCAN_CODE_SCROLL_LOCK           0x46
#define KEY_SCAN_CODE_HOME                  0x47
#define KEY_SCAN_CODE_UP                    0x48
#define KEY_SCAN_CODE_PAGE_UP               0x49
#define KEY_SCAN_CODE_KEYPAD_MINUS          0x4A
#define KEY_SCAN_CODE_LEFT                  0x4B
#define KEY_SCAN_CODE_KEYPAD_5              0x4C
#define KEY_SCAN_CODE_RIGHT                 0x4D
#define KEY_SCAN_CODE_KEYPAD_PLUS           0x4E
#define KEY_SCAN_CODE_END                   0x4F
#define KEY_SCAN_CODE_DOWN                  0x50
#define KEY_SCAN_CODE_PAGE_DOWN             0x51
#define KEY_SCAN_CODE_INSERT                0x52
#define KEY_SCAN_CODE_DELETE                0x53
#define KEY_SCAN_CODE_F11                   0x57
#define KEY_SCAN_CODE_F12                   0x58

#endif